/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTranslateRouteImport } from './routes/api/translate'
import { Route as ApiSynonymsRouteImport } from './routes/api/synonyms'
import { Route as ApiMeaningRouteImport } from './routes/api/meaning'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSynonymsRoute = ApiSynonymsRouteImport.update({
  id: '/api/synonyms',
  path: '/api/synonyms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeaningRoute = ApiMeaningRouteImport.update({
  id: '/api/meaning',
  path: '/api/meaning',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/meaning': typeof ApiMeaningRoute
  '/api/synonyms': typeof ApiSynonymsRoute
  '/api/translate': typeof ApiTranslateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/meaning': typeof ApiMeaningRoute
  '/api/synonyms': typeof ApiSynonymsRoute
  '/api/translate': typeof ApiTranslateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/meaning': typeof ApiMeaningRoute
  '/api/synonyms': typeof ApiSynonymsRoute
  '/api/translate': typeof ApiTranslateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/meaning'
    | '/api/synonyms'
    | '/api/translate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/chat' | '/api/meaning' | '/api/synonyms' | '/api/translate'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/meaning'
    | '/api/synonyms'
    | '/api/translate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiMeaningRoute: typeof ApiMeaningRoute
  ApiSynonymsRoute: typeof ApiSynonymsRoute
  ApiTranslateRoute: typeof ApiTranslateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/synonyms': {
      id: '/api/synonyms'
      path: '/api/synonyms'
      fullPath: '/api/synonyms'
      preLoaderRoute: typeof ApiSynonymsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meaning': {
      id: '/api/meaning'
      path: '/api/meaning'
      fullPath: '/api/meaning'
      preLoaderRoute: typeof ApiMeaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiMeaningRoute: ApiMeaningRoute,
  ApiSynonymsRoute: ApiSynonymsRoute,
  ApiTranslateRoute: ApiTranslateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
